var t2;var l;var tm;var i;var total;var f;var z;var temp;var pass;var j;var anut;
//---------------------------------------------------------------------------------------------------------
function per()
{
ut1();
ut2();
hf();
fin();
anu();
}
//----------------------------------------------------------------------------------------------------------
function ut1()
{
l=document.getElementById("main").rows.length;
l=l-9;
tm=20;
i=1;
total=0;
pass=(.4*tm);

for(i=1;i<l;i++)
{
temp=document.getElementById("main").rows[i].cells[1].innerHTML;
if(temp=="")
{
temp="0";
}
t2=parseInt(temp);
if(t2>=0)
{
total=total+t2;
}
else
{
document.getElementById("main").rows[i].cells[1].innerHTML="A";
document.getElementById("main").rows[i].cells[1].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[1].style.color="red";
}
if(temp<pass)
{
document.getElementById("main").rows[i].cells[1].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[1].style.color="red";
}
}
tm=tm*(l-1);
var p=(total/tm*100);
if(p<100)
{
z=p.toString();
if(z.length <=2)
{
f=z;
}
else
{
f=z.substring(0,4);
}
}
else
{
f=100;
}
document.getElementById("main").rows[l+4].cells[1].innerHTML=f+"%";
}
//-------------------------------------------------------------------------------------------------------
function ut2()
{
l=document.getElementById("main").rows.length;
l=l-9;
tm=20;
i=1;
total=0;
pass=(.4*tm);

for(i=1;i<l;i++)
{
temp=document.getElementById("main").rows[i].cells[2].innerHTML;
if(temp=="")
{
temp="0";
}
t2=parseInt(temp);
if(t2>=0)
{
total=total+t2;
}
else
{
document.getElementById("main").rows[i].cells[2].innerHTML="A";
document.getElementById("main").rows[i].cells[2].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[2].style.color="red";
}
if(temp<pass)
{
document.getElementById("main").rows[i].cells[2].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[2].style.color="red";
}
}
tm=tm*(l-1);
var p=(total/tm*100);
if(p<100)
{
z=p.toString();
if(z.length <=2)
{
f=z;
}
else
{
f=z.substring(0,4);
}
}
else
{
f=100;
}
document.getElementById("main").rows[l+4].cells[2].innerHTML=f+"%";
}
//--------------------------------------------------------------------------------------
function fin()
{
l=document.getElementById("main").rows.length;
l=l-9;
tm=100;
i=1;
total=0;
pass=(.4*tm);

for(i=1;i<l;i++)
{
temp=document.getElementById("main").rows[i].cells[4].innerHTML;
if(temp=="")
{
temp="0";
}
t2=parseInt(temp);
if(t2>=0)
{
total=total+t2;
}
else
{
document.getElementById("main").rows[i].cells[4].innerHTML="A";
document.getElementById("main").rows[i].cells[4].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[4].style.color="red";
}
if(temp<pass)
{
document.getElementById("main").rows[i].cells[4].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[4].style.color="red";
}
}
tm=tm*(l-1);
var p=(total/tm*100);
if(p<100)
{
z=p.toString();
if(z.length <=2)
{
f=z;
}
else
{
f=z.substring(0,4);
}
}
else
{
f=100;
}
document.getElementById("main").rows[l+4].cells[4].innerHTML=f+"%";
}
//--------------------------------------------------------------------------------------
function hf()
{
l=document.getElementById("main").rows.length;
l=l-9;
tm=100;
i=1;
total=0;
pass=(.4*tm);

for(i=1;i<l;i++)
{
temp=document.getElementById("main").rows[i].cells[3].innerHTML;
if(temp=="")
{
temp="0";
}
t2=parseInt(temp);
if(t2>=0)
{
total=total+t2;
}
else
{
document.getElementById("main").rows[i].cells[3].innerHTML="A";
document.getElementById("main").rows[i].cells[3].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[3].style.color="red";
}
if(temp<pass)
{
document.getElementById("main").rows[i].cells[3].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[3].style.color="red";
}
}
tm=tm*(l-1);
var p=(total/tm*100);
if(p<100)
{
z=p.toString();
if(z.length <=2)
{
f=z;
}
else
{
f=z.substring(0,4);
}
}
else
{
f=100;
}
document.getElementById("main").rows[l+4].cells[3].innerHTML=f+"%";
}
//--------------------------------------------------------------------------------------
function anu()
{
l=document.getElementById("main").rows.length;
l=l-9;
tm=100;
i=1;
total=0;
pass=(.4*tm);
et=0;
for(i=1;i<l;i++)
{
for(j=1;j<=4;j++)
{
temp=document.getElementById("main").rows[i].cells[j].innerHTML;
if(temp=="")
{
temp="0";
}
t2=parseInt(temp);
if(t2>=0)
{
et=et+t2;
}
}
et=Math.round(et/240*100);
total=total+et;
document.getElementById("main").rows[i].cells[5].innerHTML=et;
if(et<pass)
{
document.getElementById("main").rows[i].cells[5].style.fontWeight="bold";
document.getElementById("main").rows[i].cells[5].style.color="red";
}
et=0;
}
tm=tm*(l-1);
var p=(total/tm*100);
if(p<100)
{
z=p.toString();
if(z.length <=2)
{
f=z;
}
else
{
f=z.substring(0,4);
}
}
else
{
f=100;
}
document.getElementById("main").rows[l+4].cells[5].innerHTML=f+"%";
}
